name: judgment config file for vision arena bench

bench_name: release_bench_0617

# Arena Hard default
judge_model: gpt-4o #gpt-4-turbo-2024-04-09
reference: False # Optional
ref_model: null  

baseline: True
baseline_model: claude-3-sonnet-20240229 # gpt-4-turbo-2024-04-09

pairwise: False

temperature: 0
max_tokens: 4096

regex_pattern: \[\[([AB<>=]+)\]\]

system_prompt: "Please act as an impartial judge and evaluate the quality of the responses provided by two AI assistants to the user prompt displayed below. You will be given assistant A's answer and assistant B's answer. Your job is to evaluate which assistant's answer is better.\n\nBegin your evaluation by generating your own answer to the prompt. You must provide your answers before judging any answers.\n\nWhen evaluating the assistants' answers, compare both assistants' answers with your answer. You must identify and correct any mistakes or inaccurate information.\n\nThen consider if the assistant's answers are helpful, relevant, and concise. Helpful means the answer correctly responds to the prompt or follows the instructions. Note when user prompt has any ambiguity or more than one interpretation, it is more helpful and appropriate to ask for clarifications or more information from the user than providing an answer based on assumptions. Relevant means all parts of the response closely connect or are appropriate to what is being asked. Concise means the response is clear and not verbose or excessive.\n\nThen consider the creativity and novelty of the assistant's answers when needed. Finally, identify any missing important information in the assistants' answers that would be beneficial to include when responding to the user prompt.\n\nAfter providing your explanation, you must output only one of the following choices as your final verdict with a label:\n\n1. Assistant A is significantly better: [[A>>B]]\n2. Assistant A is slightly better: [[A>B]]\n3. Tie, relatively the same: [[A=B]]\n4. Assistant B is slightly better: [[B>A]]\n5. Assistant B is significantly better: [[B>>A]]\n\nExample output: \"My final verdict is tie: [[A=B]]\"."

prompt_template: ["<|User Prompt|>\n{question_1}\n\n<|The Start of Assistant A's Answer|>\n{answer_1}\n<|The End of Assistant A's Answer|>\n\n<|The Start of Assistant B's Answer|>\n{answer_2}\n<|The End of Assistant B's Answer|>"]

# Add your model below for evaluation
model_list:
  - gpt-4-vision-preview
  - gpt-4o
  - BAAI/Bunny-v1_0-3B
  - bczhou/tiny-llava-v1-hf
  - deepseek-ai/deepseek-vl-7b-chat
  - liuhaotian/llava-v1.5-13b
  - liuhaotian/llava-v1.6-vicuna-7b
  - liuhaotian/llava-v1.6-vicuna-13b
  - openbmb/MiniCPM-V
  - THUDM/cogvlm-chat-hf
  - unum-cloud/uform-gen2-qwen-500m
  - claude-3-haiku-20240307
  - claude-3-opus-20240229
  - claude-3-sonnet-20240229
  - liuhaotian/llava-v1.6-34b
  - yi-vl-plus
  - Qwen/Qwen-VL-Chat
  - idefics2-8b-chatty
  - gemini-pro-vision
  - gpt-4-turbo-2024-04-09
  - Reka-Flash